services:
  metabase:
    image: metabase/metabase:v0.51.1.1
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    expose:
      - 3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase_db
    networks:
      - app
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase_db:
    image: postgres:16-alpine
    container_name: metabase_db
    hostname: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
    ports:
      - 5433:5432
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
    name: app
    external: true

volumes:
  metabase_db_data:
    name: metabase_db_data