services:

  outline:
    image: outlinewiki/outline
    env_file: ./docker.env
    hostname: outline
    container_name: outline
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - outline

  redis:
    image: redis
    env_file: ./docker.env
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'POSTGRES_USER'
      POSTGRES_PASSWORD: 'POSTGRES_PASSWORD'
      POSTGRES_DB: 'outline'
    networks:
      - outline

volumes:
  database-data:

networks:
  outline:
    name: outline
    external: true