volumes:
  wordpress_data:
    name: wordpress_data
  db_data:
    name: db_data

networks:
  wordpress:
    name: wordpress

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress

  wordpress_db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    hostname: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: wordpress_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - wordpress
