services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:5.0.13
    networks:
      - graylog
    volumes:
      - graylog-mongo-data:/data/db

  datanode:
    image: graylog/graylog-datanode:5.2
    hostname: datanode
    container_name: datanode
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - graylog
    volumes:
      - graylog-datanode:/var/lib/graylog-datanode
    restart: on-failure

  graylog:
    image: graylog/graylog:5.2
    hostname: graylog
    container_name: graylog
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    networks:
      - graylog
    restart: on-failure
    volumes:
      - graylog-data:/usr/share/graylog/data
      - graylog-journal:/usr/share/graylog/data/journal
    depends_on:
      mongodb:
        condition: "service_started"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW TCP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
networks:
  graylog:
    name: graylog
    driver: bridge

volumes:
  graylog-mongo-data:
    name: graylog-mongo-data
  graylog-datanode:
    name: graylog-datanode
  graylog-journal:
    name: graylog-journal
  graylog-data:
    name: graylog-data