version: '3.8'
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-09-07T22-25-02Z
  command: minio server /data/minio/ --console-address ":9001" 
  ports:
    - 9000:9000
    - 9001:9001
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
services:
  minio:
    <<: *minio-common
    hostname: minio
    container_name: minio
    volumes:
      - minio:/data
volumes:
  minio:
    name: minio