version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    name: postgres_data
