version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - './redis:/var/lib/redis'
    user: root

